<?php

namespace Achie\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchievementCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementCategoryRepository extends EntityRepository
{
}
