<?php

namespace Achie\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApprovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovementRepository extends EntityRepository
{
}
