parameters:
#    achie_frontend.example.class: Achie\FrontendBundle\Example

services:
#    achie_frontend.example:
#        class: %achie_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
