achie_backend_usergotachievement:
    pattern:  /
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:index" }

achie_backend_usergotachievement_show:
    pattern:  /{id}/show
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:show" }

achie_backend_usergotachievement_new:
    pattern:  /new
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:new" }

achie_backend_usergotachievement_create:
    pattern:  /create
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:create" }
    requirements: { _method: post }

achie_backend_usergotachievement_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:edit" }

achie_backend_usergotachievement_update:
    pattern:  /{id}/update
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:update" }
    requirements: { _method: post|put }

achie_backend_usergotachievement_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AchieBackendBundle:UserGotAchievement:delete" }
    requirements: { _method: post|delete }
