achie_frontend_event:
    pattern:  /
    defaults: { _controller: "AchieFrontendBundle:Event:index" }

achie_frontend_event_show:
    pattern:  /{id}/show
    defaults: { _controller: "AchieFrontendBundle:Event:show" }



